language: java

addons:
  sonarcloud:
    organization: "mirkobaffo"
    token:
      secure: "OrZ/TubGny11raYpEjjO6IhOru/sx6gvF0Q+/WQQhOPPQWclAcK5/DhjIgqraw7qwYIgaP7CxUGh5w9C3OX6RPWZ16G5y5fjdWTM5wZDUwBj8Qq3D+585jVpZCe+GtQD6BwbKEVqlJujvDbeV03KVVgspsAvksX+CFgRffG0K6KFEV672JVBONZEM4pu523gYnP5RymjqJ7hMGFENdcDtAewSGoDlnpzUa5orPUrzPMWaOVBNYyI1febpwzvmkXcdbeE2etJnDzrFEyWt3asPIoUfqkhTvvCa5ce4QcSzuIvtNV+Sc4NArp0nq5kf6FTLOd6XxNYdfh1+brxnXjXhV02PtZ0bdhFBZIS3QQTOb3xfILHvqK953Wgn0fCK5sSsyjxr/6hArYHts6eHU0HysI9Fcn5HaQ7UUNGkSdO3aOBJ3Bh+T1lRXSeEV+WrT0B6JiPiqmi5NB9rZQtl2J0I6b5hvAh6oLpwElrLfHadJBF/PF095+3be9oYZWvpXyGqcaTLBqFWev6lquOpJsgHizrSutiM0kR1wpIhkC4TQ0lsEpkw/6efjqVNYDQBzcjGLuDkvWnFFW2Gm5AvKlp9oGJ8oMqKlLnudPDvW7EbB/P1K/gX6XwqEpct+1XFqIYXIDyi1teRQwM8NAdakfOY44DvOk+UjrTWsMSj7u7rnE=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mirkobaffo_progetto2_bookkeeper_test
